# Python CI/CD Pipeline Template
# Usage: Copy to .github/workflows/ci.yml and customize

name: Python CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  PYTHON_VERSION: '3.11'

jobs:
  # ============================================
  # Lint and Type Check
  # ============================================
  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy
          pip install -r requirements.txt

      - name: Run Ruff (linting)
        run: ruff check .

      - name: Run Ruff (formatting check)
        run: ruff format --check .

      - name: Run MyPy (type checking)
        run: mypy src/ --ignore-missing-imports

  # ============================================
  # Unit & Integration Tests
  # ============================================
  test:
    name: Test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    services:
      # Uncomment if tests need PostgreSQL
      # postgres:
      #   image: postgres:15
      #   env:
      #     POSTGRES_USER: test
      #     POSTGRES_PASSWORD: test
      #     POSTGRES_DB: test
      #   ports:
      #     - 5432:5432
      #   options: >-
      #     --health-cmd pg_isready
      #     --health-interval 10s
      #     --health-timeout 5s
      #     --health-retries 5

      # Uncomment if tests need Redis
      # redis:
      #   image: redis:7
      #   ports:
      #     - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run tests with pytest
        run: |
          pytest \
            --cov=src \
            --cov-report=xml \
            --cov-report=html \
            --junitxml=junit.xml \
            -v
        env:
          # DATABASE_URL: postgresql://test:test@localhost:5432/test
          # REDIS_URL: redis://localhost:6379

      - name: Upload coverage to Codecov
        if: matrix.python-version == '3.11'
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.python-version }}
          path: |
            junit.xml
            htmlcov/

  # ============================================
  # Build Package
  # ============================================
  build:
    name: Build Package
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install build tools
        run: pip install build twine

      - name: Build package
        run: python -m build

      - name: Check package
        run: twine check dist/*

      - name: Upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package
          path: dist/

  # ============================================
  # Security Audit
  # ============================================
  security:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install safety bandit
          pip install -r requirements.txt

      - name: Run Safety (dependency vulnerabilities)
        run: safety check
        continue-on-error: true

      - name: Run Bandit (code security)
        run: bandit -r src/ -ll
        continue-on-error: true

  # ============================================
  # Publish to PyPI (on tag)
  # ============================================
  # publish:
  #   name: Publish to PyPI
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   if: startsWith(github.ref, 'refs/tags/v')
  #   environment:
  #     name: pypi
  #     url: https://pypi.org/project/your-package/
  #
  #   steps:
  #     - name: Download package
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: python-package
  #         path: dist/
  #
  #     - name: Publish to PyPI
  #       uses: pypa/gh-action-pypi-publish@release/v1
  #       with:
  #         password: ${{ secrets.PYPI_API_TOKEN }}
