name: Feature Request
description: Suggest a new feature or enhancement for the Developer Kit plugin
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand your request.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New Skill
        - New Agent
        - New Command
        - New Hook
        - New MCP Server Integration
        - New Template
        - Enhancement to Existing Component
        - Documentation Improvement
        - Developer Experience
        - Other
    validations:
      required: true

  - type: input
    id: component-name
    attributes:
      label: Component Name (if applicable)
      description: If this is an enhancement to an existing component, which one?
      placeholder: "e.g., implement skill, architect agent"
    validations:
      required: false

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: |
        As a [user type], I want to [do something] so that [benefit].
        Currently, I have to [workaround], which is [problem].
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your ideal solution in detail.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or features have you considered?
      placeholder: Describe any alternative approaches you've thought about.
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Show how you would use this feature
      placeholder: |
        # Example usage
        /new-command arg1 arg2

        or

        skill: my-new-skill
        trigger: "implement feature X"
      render: markdown
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Critical - Blocking my work"
        - "High - Significantly improves my workflow"
        - "Medium - Nice to have"
        - "Low - Minor enhancement"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
    validations:
      required: false

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      options:
        - label: I would be willing to implement this feature
        - label: I would be willing to help test this feature
        - label: I would be willing to write documentation for this feature

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues and discussions to avoid duplicates
          required: true
        - label: I have read the [CONTRIBUTING.md](../CONTRIBUTING.md) guidelines
          required: true
        - label: This feature aligns with the project's goals
          required: true
