#!/bin/bash
# save-session-state.sh - Stop hook for session state persistence
# Returns JSON response per Claude Code hook specification

# Determine project directory
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(pwd)}"
SESSION_DIR="$PROJECT_DIR/docs/session"
LAST_SESSION="$SESSION_DIR/last-session.md"
CURRENT_CONTEXT="$SESSION_DIR/current-context.md"

# Only create session files if docs/ directory exists (project uses session tracking)
if [ ! -d "$PROJECT_DIR/docs" ]; then
    echo '{"continue": true, "suppressOutput": true}'
    exit 0
fi

# Ensure session directory exists
mkdir -p "$SESSION_DIR" 2>/dev/null

# Get current timestamp and branch
DATE=$(date '+%Y-%m-%d %H:%M')
BRANCH="unknown"
if command -v git &> /dev/null && [ -d "$PROJECT_DIR/.git" ]; then
    BRANCH=$(cd "$PROJECT_DIR" && git branch --show-current 2>/dev/null || echo "unknown")
fi

# Get current goal from context if exists
GOAL="[No goal recorded]"
if [ -f "$CURRENT_CONTEXT" ]; then
    EXTRACTED_GOAL=$(grep -A1 "^## Goal" "$CURRENT_CONTEXT" 2>/dev/null | tail -1 | sed 's/^[[:space:]]*//')
    if [ -n "$EXTRACTED_GOAL" ] && [ "$EXTRACTED_GOAL" != "## Goal" ]; then
        GOAL="$EXTRACTED_GOAL"
    fi
fi

# Count completed and pending items from current context
COMPLETED=0
PENDING=0
if [ -f "$CURRENT_CONTEXT" ]; then
    COMPLETED=$(grep -c "^\- \[x\]" "$CURRENT_CONTEXT" 2>/dev/null || echo "0")
    PENDING=$(grep -c "^\- \[ \]" "$CURRENT_CONTEXT" 2>/dev/null || echo "0")
fi

# Generate last session summary
cat > "$LAST_SESSION" << EOF
# Last Session Summary

**Date**: $DATE
**Branch**: $BRANCH

## Goal
$GOAL

## Progress
- Completed: $COMPLETED tasks
- Pending: $PENDING tasks

## Session Notes
Session ended normally. Use \`start\` to begin new work or continue from current context.

---
*Auto-generated by Developer Kit session management*
EOF

# Return JSON response
if [ -f "$LAST_SESSION" ]; then
    echo '{"continue": true, "systemMessage": "Session state saved to docs/session/"}'
else
    echo '{"continue": true, "suppressOutput": true}'
fi

exit 0
