#!/bin/bash
# save_session_state.sh
# Stop hook - save session state when session ends
#
# Creates a last-session.md summary file with:
# - Date and branch
# - Goal and progress
# - Session notes

set -euo pipefail

# Consume stdin (hook input) - we don't need it but must read it
cat > /dev/null

# Get project directory
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(pwd)}"

DOCS_DIR="$PROJECT_DIR/docs"
SESSION_DIR="$DOCS_DIR/session"
LAST_SESSION="$SESSION_DIR/last-session.md"
CURRENT_CONTEXT="$SESSION_DIR/current-context.md"

# Only create session files if docs/ directory exists
if [[ ! -d "$DOCS_DIR" ]]; then
    echo '{"continue":true,"suppressOutput":true}'
    exit 0
fi

# Ensure session directory exists
mkdir -p "$SESSION_DIR"

# Get current date
DATE_STR=$(date "+%Y-%m-%d %H:%M")

# Get current git branch
BRANCH="unknown"
if [[ -d "$PROJECT_DIR/.git" ]]; then
    BRANCH=$(git -C "$PROJECT_DIR" branch --show-current 2>/dev/null || echo "unknown")
    if [[ -z "$BRANCH" ]]; then
        BRANCH="unknown"
    fi
fi

# Get goal and progress from current context
GOAL="[No goal recorded]"
COMPLETED=0
PENDING=0

if [[ -f "$CURRENT_CONTEXT" ]]; then
    CONTENT=$(cat "$CURRENT_CONTEXT" 2>/dev/null || echo "")

    # Extract goal
    EXTRACTED_GOAL=$(echo "$CONTENT" | grep -A1 "^## Goal" 2>/dev/null | tail -1 | sed 's/^[[:space:]]*//' || echo "")
    if [[ -n "$EXTRACTED_GOAL" ]] && [[ "$EXTRACTED_GOAL" != "## Goal" ]]; then
        GOAL="$EXTRACTED_GOAL"
    fi

    # Count checkboxes
    COMPLETED=$(echo "$CONTENT" | grep -c "^- \[x\]" 2>/dev/null || echo "0")
    PENDING=$(echo "$CONTENT" | grep -c "^- \[ \]" 2>/dev/null || echo "0")
fi

# Generate and save session summary
cat > "$LAST_SESSION" << EOF
# Last Session Summary

**Date**: $DATE_STR
**Branch**: $BRANCH

## Goal
$GOAL

## Progress
- Completed: $COMPLETED tasks
- Pending: $PENDING tasks

## Session Notes
Session ended normally. Use \`start\` to begin new work or continue from current context.

---
*Auto-generated by Developer Kit session management*
EOF

echo '{"continue":true,"systemMessage":"Session state saved to docs/session/"}'
