#!/usr/bin/env python3
"""
Stop hook for session state persistence.

Returns JSON response per Claude Code hook specification.

This hook saves session state when the session ends:
- Creates a last-session.md summary file
- Records the date, branch, goal, and progress
- Only activates for projects that use session tracking (have docs/ directory)
"""

import os
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import Tuple

# Add lib directory to path for cross-platform utilities
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "lib"))

from platform_utils import HookIO, CommandRunner, PlatformInfo, FileUtils


def get_current_branch(project_dir: Path) -> str:
    """
    Get current git branch name.

    Args:
        project_dir: Project directory path.

    Returns:
        Branch name or 'unknown' if not available.
    """
    git_dir = project_dir / ".git"
    if not git_dir.exists():
        return "unknown"

    returncode, stdout, stderr = CommandRunner.run_git_command(
        ["branch", "--show-current"],
        cwd=project_dir,
        timeout=5,
    )

    return stdout.strip() if returncode == 0 and stdout.strip() else "unknown"


def extract_goal(content: str) -> str:
    """
    Extract goal from context file content.

    Args:
        content: File content.

    Returns:
        Goal text or default message.
    """
    match = re.search(r"^## Goal\s*\n(.+)", content, re.MULTILINE)
    if match:
        goal = match.group(1).strip()
        if goal and goal != "## Goal":
            return goal
    return "[No goal recorded]"


def count_checkboxes(content: str) -> Tuple[int, int]:
    """
    Count completed and pending checkboxes.

    Args:
        content: File content.

    Returns:
        Tuple of (completed_count, pending_count).
    """
    completed = len(re.findall(r"^- \[x\]", content, re.MULTILINE | re.IGNORECASE))
    pending = len(re.findall(r"^- \[ \]", content, re.MULTILINE))
    return completed, pending


def generate_session_summary(
    date_str: str,
    branch: str,
    goal: str,
    completed: int,
    pending: int,
) -> str:
    """
    Generate the last session summary markdown content.

    Args:
        date_str: Formatted date string.
        branch: Git branch name.
        goal: Session goal.
        completed: Number of completed tasks.
        pending: Number of pending tasks.

    Returns:
        Markdown content for last-session.md.
    """
    return f"""# Last Session Summary

**Date**: {date_str}
**Branch**: {branch}

## Goal
{goal}

## Progress
- Completed: {completed} tasks
- Pending: {pending} tasks

## Session Notes
Session ended normally. Use `start` to begin new work or continue from current context.

---
*Auto-generated by Developer Kit session management*
"""


def main():
    """Main hook function."""
    project_dir = PlatformInfo.get_project_dir()

    # Only create session files if docs/ directory exists
    # This indicates the project uses session tracking
    docs_dir = project_dir / "docs"
    if not docs_dir.exists():
        HookIO.allow_continue(suppress=True)
        return

    session_dir = docs_dir / "session"
    last_session = session_dir / "last-session.md"
    current_context = session_dir / "current-context.md"

    # Ensure session directory exists
    try:
        FileUtils.ensure_dir(session_dir)
    except Exception:
        HookIO.allow_continue(suppress=True)
        return

    # Get current info
    date_str = datetime.now().strftime("%Y-%m-%d %H:%M")
    branch = get_current_branch(project_dir)

    # Get goal and progress from current context
    goal = "[No goal recorded]"
    completed = 0
    pending = 0

    if current_context.exists():
        try:
            content = FileUtils.read_text(current_context)
            goal = extract_goal(content)
            completed, pending = count_checkboxes(content)
        except Exception:
            pass  # Use defaults if read fails

    # Generate and save session summary
    summary = generate_session_summary(date_str, branch, goal, completed, pending)

    try:
        FileUtils.write_text(last_session, summary)
        HookIO.allow_continue(message="Session state saved to docs/session/")
    except Exception:
        HookIO.allow_continue(suppress=True)


if __name__ == "__main__":
    main()
